### ISSUE TITLE
Master Thesis Link down in Wiki

### ISSUE THREAD

**Issue by subes** [dhonza/JCOOL#14]
Hi, I am very interested to learn more about JCool. Sadly the link to the master thesis in the wiki is offline (http://neuron.felk.cvut.cz/~drchaj1/jcool/bicikvla_2010dipl.pdf).
Can you maybe upload it again or send it via email (gsubes@gmail.com)?

Thanks a lot!

**Comment by dhonza** [comment]
Hi, I've uploaded the thesis directly to the repository. See link here: https://github.com/dhonza/JCOOL/wiki

**Comment by subes** [comment]
Thanks a lot!
